/* generated by Dries Cornilly on 2019-06-19 using tools::package_native_routine_registration_skeleton(".") */

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>

/* FIXME:
 Check these declarations against the C/Fortran source code.
 */

/* .Call calls */
extern SEXP M3mat2vec(SEXP, SEXP);
extern SEXP M3port(SEXP, SEXP, SEXP);
extern SEXP M3port_grad(SEXP, SEXP, SEXP);
extern SEXP M4mat2vec(SEXP, SEXP);
extern SEXP M4port(SEXP, SEXP, SEXP);
extern SEXP M4port_grad(SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
  {"M3mat2vec",   (DL_FUNC) &M3mat2vec,   2},
  {"M3port",      (DL_FUNC) &M3port,      3},
  {"M3port_grad", (DL_FUNC) &M3port_grad, 3},
  {"M4mat2vec",   (DL_FUNC) &M4mat2vec,   2},
  {"M4port",      (DL_FUNC) &M4port,      3},
  {"M4port_grad", (DL_FUNC) &M4port_grad, 3},
  {NULL, NULL, 0}
};

void R_init_mvskPortfolios(DllInfo *dll)
{
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
